spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://ec2-54-243-253-181.compute-1.amazonaws.com:5432/d953i231tmtnlp
    username: eamjiigsjvvsoq
    password: 7e85b51ee0e623a23727e672a98815af26edbb9b410b8f3be286ffda8243964d
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

oauth-clients:
  guia_de_projeto_api:
    client: guia-de-projeto-api-client
    secret: guia-de-projeto-api-secret