spring:
  datasource:
    url: jdbc:postgresql://sqlvhnegrisoli.ddns.net:5432/guia_de_projeto
#    url: jdbc:postgresql://localhost:5432/guia_de_projeto
    username: postgres
    password: 1y5h8j
    initialization-mode: always
    initialize: true
    continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

oauth-clients:
  guia_de_projeto_api:
    client: guia-de-projeto-api-client
    secret: guia-de-projeto-api-secret